/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthedAdminRouteRouteImport } from './routes/_authed/admin/route'
import { Route as AuthedCalendarIndexRouteImport } from './routes/_authed/calendar/index'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedCalendarTemplatesRouteRouteImport } from './routes/_authed/calendar/templates/route'
import { Route as AuthedCalendarTemplatesIndexRouteImport } from './routes/_authed/calendar/templates/index'
import { Route as AuthedAdminUsersIndexRouteImport } from './routes/_authed/admin/users/index'
import { Route as AuthedCalendarTemplatesNewRouteImport } from './routes/_authed/calendar/templates/new'
import { Route as AuthedCalendarTemplatesTemplateIdRouteImport } from './routes/_authed/calendar/templates/$templateId'
import { Route as AuthedCalendarEventsNewRouteImport } from './routes/_authed/calendar/events.new'
import { Route as AuthedCalendarEventsEventIdRouteImport } from './routes/_authed/calendar/events.$eventId'
import { Route as AuthedCalendarYearMonthRouteImport } from './routes/_authed/calendar/$year.$month'
import { Route as AuthedAdminUsersUserIdRouteRouteImport } from './routes/_authed/admin/users/$userId/route'
import { Route as AuthedAdminUsersUserIdIndexRouteImport } from './routes/_authed/admin/users/$userId/index'
import { Route as AuthedAdminUsersUserIdProfileRouteImport } from './routes/_authed/admin/users/$userId/profile'
import { Route as AuthedAdminUsersUserIdHistoryRouteImport } from './routes/_authed/admin/users/$userId/history'

const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthedAdminRouteRoute = AuthedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedCalendarIndexRoute = AuthedCalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedCalendarTemplatesRouteRoute =
  AuthedCalendarTemplatesRouteRouteImport.update({
    id: '/calendar/templates',
    path: '/calendar/templates',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedCalendarTemplatesIndexRoute =
  AuthedCalendarTemplatesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedCalendarTemplatesRouteRoute,
  } as any)
const AuthedAdminUsersIndexRoute = AuthedAdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedCalendarTemplatesNewRoute =
  AuthedCalendarTemplatesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthedCalendarTemplatesRouteRoute,
  } as any)
const AuthedCalendarTemplatesTemplateIdRoute =
  AuthedCalendarTemplatesTemplateIdRouteImport.update({
    id: '/$templateId',
    path: '/$templateId',
    getParentRoute: () => AuthedCalendarTemplatesRouteRoute,
  } as any)
const AuthedCalendarEventsNewRoute = AuthedCalendarEventsNewRouteImport.update({
  id: '/calendar/events/new',
  path: '/calendar/events/new',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedCalendarEventsEventIdRoute =
  AuthedCalendarEventsEventIdRouteImport.update({
    id: '/calendar/events/$eventId',
    path: '/calendar/events/$eventId',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedCalendarYearMonthRoute = AuthedCalendarYearMonthRouteImport.update({
  id: '/calendar/$year/$month',
  path: '/calendar/$year/$month',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAdminUsersUserIdRouteRoute =
  AuthedAdminUsersUserIdRouteRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthedAdminRouteRoute,
  } as any)
const AuthedAdminUsersUserIdIndexRoute =
  AuthedAdminUsersUserIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedAdminUsersUserIdRouteRoute,
  } as any)
const AuthedAdminUsersUserIdProfileRoute =
  AuthedAdminUsersUserIdProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthedAdminUsersUserIdRouteRoute,
  } as any)
const AuthedAdminUsersUserIdHistoryRoute =
  AuthedAdminUsersUserIdHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthedAdminUsersUserIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/pending': typeof PendingRoute
  '/admin': typeof AuthedAdminRouteRouteWithChildren
  '/register': typeof AuthRegisterRoute
  '/sign-in': typeof AuthSignInRoute
  '/calendar/templates': typeof AuthedCalendarTemplatesRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/calendar/': typeof AuthedCalendarIndexRoute
  '/admin/users/$userId': typeof AuthedAdminUsersUserIdRouteRouteWithChildren
  '/calendar/$year/$month': typeof AuthedCalendarYearMonthRoute
  '/calendar/events/$eventId': typeof AuthedCalendarEventsEventIdRoute
  '/calendar/events/new': typeof AuthedCalendarEventsNewRoute
  '/calendar/templates/$templateId': typeof AuthedCalendarTemplatesTemplateIdRoute
  '/calendar/templates/new': typeof AuthedCalendarTemplatesNewRoute
  '/admin/users/': typeof AuthedAdminUsersIndexRoute
  '/calendar/templates/': typeof AuthedCalendarTemplatesIndexRoute
  '/admin/users/$userId/history': typeof AuthedAdminUsersUserIdHistoryRoute
  '/admin/users/$userId/profile': typeof AuthedAdminUsersUserIdProfileRoute
  '/admin/users/$userId/': typeof AuthedAdminUsersUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedIndexRoute
  '/pending': typeof PendingRoute
  '/register': typeof AuthRegisterRoute
  '/sign-in': typeof AuthSignInRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/calendar': typeof AuthedCalendarIndexRoute
  '/calendar/$year/$month': typeof AuthedCalendarYearMonthRoute
  '/calendar/events/$eventId': typeof AuthedCalendarEventsEventIdRoute
  '/calendar/events/new': typeof AuthedCalendarEventsNewRoute
  '/calendar/templates/$templateId': typeof AuthedCalendarTemplatesTemplateIdRoute
  '/calendar/templates/new': typeof AuthedCalendarTemplatesNewRoute
  '/admin/users': typeof AuthedAdminUsersIndexRoute
  '/calendar/templates': typeof AuthedCalendarTemplatesIndexRoute
  '/admin/users/$userId/history': typeof AuthedAdminUsersUserIdHistoryRoute
  '/admin/users/$userId/profile': typeof AuthedAdminUsersUserIdProfileRoute
  '/admin/users/$userId': typeof AuthedAdminUsersUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/pending': typeof PendingRoute
  '/_authed/admin': typeof AuthedAdminRouteRouteWithChildren
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/calendar/templates': typeof AuthedCalendarTemplatesRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/_authed/calendar/': typeof AuthedCalendarIndexRoute
  '/_authed/admin/users/$userId': typeof AuthedAdminUsersUserIdRouteRouteWithChildren
  '/_authed/calendar/$year/$month': typeof AuthedCalendarYearMonthRoute
  '/_authed/calendar/events/$eventId': typeof AuthedCalendarEventsEventIdRoute
  '/_authed/calendar/events/new': typeof AuthedCalendarEventsNewRoute
  '/_authed/calendar/templates/$templateId': typeof AuthedCalendarTemplatesTemplateIdRoute
  '/_authed/calendar/templates/new': typeof AuthedCalendarTemplatesNewRoute
  '/_authed/admin/users/': typeof AuthedAdminUsersIndexRoute
  '/_authed/calendar/templates/': typeof AuthedCalendarTemplatesIndexRoute
  '/_authed/admin/users/$userId/history': typeof AuthedAdminUsersUserIdHistoryRoute
  '/_authed/admin/users/$userId/profile': typeof AuthedAdminUsersUserIdProfileRoute
  '/_authed/admin/users/$userId/': typeof AuthedAdminUsersUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pending'
    | '/admin'
    | '/register'
    | '/sign-in'
    | '/calendar/templates'
    | '/api/auth/$'
    | '/admin/'
    | '/calendar/'
    | '/admin/users/$userId'
    | '/calendar/$year/$month'
    | '/calendar/events/$eventId'
    | '/calendar/events/new'
    | '/calendar/templates/$templateId'
    | '/calendar/templates/new'
    | '/admin/users/'
    | '/calendar/templates/'
    | '/admin/users/$userId/history'
    | '/admin/users/$userId/profile'
    | '/admin/users/$userId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pending'
    | '/register'
    | '/sign-in'
    | '/api/auth/$'
    | '/admin'
    | '/calendar'
    | '/calendar/$year/$month'
    | '/calendar/events/$eventId'
    | '/calendar/events/new'
    | '/calendar/templates/$templateId'
    | '/calendar/templates/new'
    | '/admin/users'
    | '/calendar/templates'
    | '/admin/users/$userId/history'
    | '/admin/users/$userId/profile'
    | '/admin/users/$userId'
  id:
    | '__root__'
    | '/_auth'
    | '/_authed'
    | '/pending'
    | '/_authed/admin'
    | '/_auth/register'
    | '/_auth/sign-in'
    | '/_authed/'
    | '/_authed/calendar/templates'
    | '/api/auth/$'
    | '/_authed/admin/'
    | '/_authed/calendar/'
    | '/_authed/admin/users/$userId'
    | '/_authed/calendar/$year/$month'
    | '/_authed/calendar/events/$eventId'
    | '/_authed/calendar/events/new'
    | '/_authed/calendar/templates/$templateId'
    | '/_authed/calendar/templates/new'
    | '/_authed/admin/users/'
    | '/_authed/calendar/templates/'
    | '/_authed/admin/users/$userId/history'
    | '/_authed/admin/users/$userId/profile'
    | '/_authed/admin/users/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  PendingRoute: typeof PendingRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/calendar/': {
      id: '/_authed/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof AuthedCalendarIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/calendar/templates': {
      id: '/_authed/calendar/templates'
      path: '/calendar/templates'
      fullPath: '/calendar/templates'
      preLoaderRoute: typeof AuthedCalendarTemplatesRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/calendar/templates/': {
      id: '/_authed/calendar/templates/'
      path: '/'
      fullPath: '/calendar/templates/'
      preLoaderRoute: typeof AuthedCalendarTemplatesIndexRouteImport
      parentRoute: typeof AuthedCalendarTemplatesRouteRoute
    }
    '/_authed/admin/users/': {
      id: '/_authed/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthedAdminUsersIndexRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/calendar/templates/new': {
      id: '/_authed/calendar/templates/new'
      path: '/new'
      fullPath: '/calendar/templates/new'
      preLoaderRoute: typeof AuthedCalendarTemplatesNewRouteImport
      parentRoute: typeof AuthedCalendarTemplatesRouteRoute
    }
    '/_authed/calendar/templates/$templateId': {
      id: '/_authed/calendar/templates/$templateId'
      path: '/$templateId'
      fullPath: '/calendar/templates/$templateId'
      preLoaderRoute: typeof AuthedCalendarTemplatesTemplateIdRouteImport
      parentRoute: typeof AuthedCalendarTemplatesRouteRoute
    }
    '/_authed/calendar/events/new': {
      id: '/_authed/calendar/events/new'
      path: '/calendar/events/new'
      fullPath: '/calendar/events/new'
      preLoaderRoute: typeof AuthedCalendarEventsNewRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/calendar/events/$eventId': {
      id: '/_authed/calendar/events/$eventId'
      path: '/calendar/events/$eventId'
      fullPath: '/calendar/events/$eventId'
      preLoaderRoute: typeof AuthedCalendarEventsEventIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/calendar/$year/$month': {
      id: '/_authed/calendar/$year/$month'
      path: '/calendar/$year/$month'
      fullPath: '/calendar/$year/$month'
      preLoaderRoute: typeof AuthedCalendarYearMonthRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/admin/users/$userId': {
      id: '/_authed/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AuthedAdminUsersUserIdRouteRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/users/$userId/': {
      id: '/_authed/admin/users/$userId/'
      path: '/'
      fullPath: '/admin/users/$userId/'
      preLoaderRoute: typeof AuthedAdminUsersUserIdIndexRouteImport
      parentRoute: typeof AuthedAdminUsersUserIdRouteRoute
    }
    '/_authed/admin/users/$userId/profile': {
      id: '/_authed/admin/users/$userId/profile'
      path: '/profile'
      fullPath: '/admin/users/$userId/profile'
      preLoaderRoute: typeof AuthedAdminUsersUserIdProfileRouteImport
      parentRoute: typeof AuthedAdminUsersUserIdRouteRoute
    }
    '/_authed/admin/users/$userId/history': {
      id: '/_authed/admin/users/$userId/history'
      path: '/history'
      fullPath: '/admin/users/$userId/history'
      preLoaderRoute: typeof AuthedAdminUsersUserIdHistoryRouteImport
      parentRoute: typeof AuthedAdminUsersUserIdRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthSignInRoute: typeof AuthSignInRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthRegisterRoute: AuthRegisterRoute,
  AuthSignInRoute: AuthSignInRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AuthedAdminUsersUserIdRouteRouteChildren {
  AuthedAdminUsersUserIdHistoryRoute: typeof AuthedAdminUsersUserIdHistoryRoute
  AuthedAdminUsersUserIdProfileRoute: typeof AuthedAdminUsersUserIdProfileRoute
  AuthedAdminUsersUserIdIndexRoute: typeof AuthedAdminUsersUserIdIndexRoute
}

const AuthedAdminUsersUserIdRouteRouteChildren: AuthedAdminUsersUserIdRouteRouteChildren =
  {
    AuthedAdminUsersUserIdHistoryRoute: AuthedAdminUsersUserIdHistoryRoute,
    AuthedAdminUsersUserIdProfileRoute: AuthedAdminUsersUserIdProfileRoute,
    AuthedAdminUsersUserIdIndexRoute: AuthedAdminUsersUserIdIndexRoute,
  }

const AuthedAdminUsersUserIdRouteRouteWithChildren =
  AuthedAdminUsersUserIdRouteRoute._addFileChildren(
    AuthedAdminUsersUserIdRouteRouteChildren,
  )

interface AuthedAdminRouteRouteChildren {
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
  AuthedAdminUsersUserIdRouteRoute: typeof AuthedAdminUsersUserIdRouteRouteWithChildren
  AuthedAdminUsersIndexRoute: typeof AuthedAdminUsersIndexRoute
}

const AuthedAdminRouteRouteChildren: AuthedAdminRouteRouteChildren = {
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
  AuthedAdminUsersUserIdRouteRoute:
    AuthedAdminUsersUserIdRouteRouteWithChildren,
  AuthedAdminUsersIndexRoute: AuthedAdminUsersIndexRoute,
}

const AuthedAdminRouteRouteWithChildren =
  AuthedAdminRouteRoute._addFileChildren(AuthedAdminRouteRouteChildren)

interface AuthedCalendarTemplatesRouteRouteChildren {
  AuthedCalendarTemplatesTemplateIdRoute: typeof AuthedCalendarTemplatesTemplateIdRoute
  AuthedCalendarTemplatesNewRoute: typeof AuthedCalendarTemplatesNewRoute
  AuthedCalendarTemplatesIndexRoute: typeof AuthedCalendarTemplatesIndexRoute
}

const AuthedCalendarTemplatesRouteRouteChildren: AuthedCalendarTemplatesRouteRouteChildren =
  {
    AuthedCalendarTemplatesTemplateIdRoute:
      AuthedCalendarTemplatesTemplateIdRoute,
    AuthedCalendarTemplatesNewRoute: AuthedCalendarTemplatesNewRoute,
    AuthedCalendarTemplatesIndexRoute: AuthedCalendarTemplatesIndexRoute,
  }

const AuthedCalendarTemplatesRouteRouteWithChildren =
  AuthedCalendarTemplatesRouteRoute._addFileChildren(
    AuthedCalendarTemplatesRouteRouteChildren,
  )

interface AuthedRouteRouteChildren {
  AuthedAdminRouteRoute: typeof AuthedAdminRouteRouteWithChildren
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedCalendarTemplatesRouteRoute: typeof AuthedCalendarTemplatesRouteRouteWithChildren
  AuthedCalendarIndexRoute: typeof AuthedCalendarIndexRoute
  AuthedCalendarYearMonthRoute: typeof AuthedCalendarYearMonthRoute
  AuthedCalendarEventsEventIdRoute: typeof AuthedCalendarEventsEventIdRoute
  AuthedCalendarEventsNewRoute: typeof AuthedCalendarEventsNewRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedAdminRouteRoute: AuthedAdminRouteRouteWithChildren,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedCalendarTemplatesRouteRoute:
    AuthedCalendarTemplatesRouteRouteWithChildren,
  AuthedCalendarIndexRoute: AuthedCalendarIndexRoute,
  AuthedCalendarYearMonthRoute: AuthedCalendarYearMonthRoute,
  AuthedCalendarEventsEventIdRoute: AuthedCalendarEventsEventIdRoute,
  AuthedCalendarEventsNewRoute: AuthedCalendarEventsNewRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  PendingRoute: PendingRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
